from fastapi import APIRouter, File, Form, UploadFile, HTTPException

from app.schemas.analysis import AnalysisResponse
from app.schemas.pipeline import AnalyzeCvRequest, AnalyzeCvResponse, AnalyzeJobRequest, AnalyzeJobResponse
from app.services.cv_parser import parse_cv
from app.services.llm import LLMServiceError, analyze_cv_text, analyze_job_text

router = APIRouter()


@router.post("", response_model=AnalysisResponse)
async def analyze_cv(
    file: UploadFile = File(...),
    job_description: str = Form(...),
) -> AnalysisResponse:
    file_bytes = await file.read()
    parsed = parse_cv(file_bytes=file_bytes, filename=file.filename or "")
    return AnalysisResponse(
        score=0,
        missing_keywords=[],
        optimized_cv=parsed.raw_text,
        feedback="Stage 3: extracted plain text from CV PDF/TXT.",
    )


@router.post("/cv", response_model=AnalyzeCvResponse)
def analyze_cv_text_route(payload: AnalyzeCvRequest) -> AnalyzeCvResponse:
    try:
        analysis = analyze_cv_text(payload.cv_text)
    except LLMServiceError as exc:
        raise HTTPException(status_code=exc.status_code, detail=str(exc)) from exc
    except Exception as exc:
        raise HTTPException(status_code=500, detail="Unexpected server error") from exc

    return AnalyzeCvResponse(
        cv_analysis=analysis,
        feedback="CV analysis generated by LLM.",
    )


@router.post("/job", response_model=AnalyzeJobResponse)
def analyze_job_text_route(payload: AnalyzeJobRequest) -> AnalyzeJobResponse:
    try:
        analysis = analyze_job_text(payload.job_text)
    except LLMServiceError as exc:
        raise HTTPException(status_code=exc.status_code, detail=str(exc)) from exc
    except Exception as exc:
        raise HTTPException(status_code=500, detail="Unexpected server error") from exc

    return AnalyzeJobResponse(
        job_analysis=analysis,
        feedback="Job analysis generated by LLM.",
    )
