from dataclasses import dataclass

from google import genai
from google.genai import errors as genai_errors

from app.core.config import settings


@dataclass
class LLMResult:
    optimized_cv: str
    feedback: str


def generate_optimized_cv(cv_text: str, job_text: str) -> LLMResult:
    return _generate_with_gemini(cv_text=cv_text, job_text=job_text)


def _generate_with_gemini(cv_text: str, job_text: str) -> LLMResult:
    if not settings.gemini_api_key:
        raise RuntimeError("GEMINI_API_KEY is not set")

    client = genai.Client(api_key=settings.gemini_api_key)

    prompt = (
        "You are a CV optimization assistant. Improve the CV to match the job description. "
        "Keep the language professional and concise.\n\n"
        f"CV:\n{cv_text}\n\n"
        f"Job description:\n{job_text}\n\n"
        "Return the improved CV text."
    )

    try:
        response = client.models.generate_content(
            model=settings.gemini_model,
            contents=prompt,
        )
    except genai_errors.ClientError as exc:
        raise RuntimeError(f"GEMINI_ERROR: {exc}") from exc
    except Exception as exc:
        raise RuntimeError(f"GEMINI_ERROR: {exc}") from exc

    optimized_cv = (getattr(response, "text", "") or "").strip()
    if not optimized_cv:
        raise RuntimeError("GEMINI_ERROR: empty response")
    return LLMResult(
        optimized_cv=optimized_cv,
        feedback="Generated by Gemini API.",
    )
