from dataclasses import dataclass
from functools import lru_cache
import logging

from google import genai
from google.genai import errors as genai_errors

from app.core.config import settings

logger = logging.getLogger(__name__)


@dataclass
class LLMResult:
    optimized_cv: str
    feedback: str


class LLMServiceError(RuntimeError):
    def __init__(self, message: str, status_code: int = 502) -> None:
        super().__init__(message)
        self.status_code = status_code


def generate_optimized_cv(cv_text: str, job_text: str) -> LLMResult:
    cv_text = _truncate(cv_text, settings.max_cv_chars)
    job_text = _truncate(job_text, settings.max_job_chars)
    return _generate_with_gemini(cv_text=cv_text, job_text=job_text)


def _generate_with_gemini(cv_text: str, job_text: str) -> LLMResult:
    if not settings.gemini_api_key:
        raise LLMServiceError("GEMINI_API_KEY is not set", status_code=500)

    client = _get_gemini_client()

    prompt = (
        "You are an expert CV optimizer. Rewrite the CV to match the job description.\n"
        "Goal: increase ATS match and hiring-manager clarity by 2–3x.\n\n"
        "Rules:\n"
        "- Use strong action verbs at the start of each bullet.\n"
        "- Keep an ATS-friendly, keyword-rich style aligned to the job description.\n"
        "- Use bullet points for experience and achievements.\n"
        "- Keep structure clean and scannable (section headers + bullets).\n"
        "- Preserve truthful content; do not invent skills, tools, or employers.\n"
        "- Prefer quantified impact (%, $, time saved, scale, volume) when present.\n"
        "- Remove fluff, tighten wording, keep it concise.\n"
        "- Output ONLY the improved CV text (no explanations, no extra labels).\n\n"
        f"CV:\n{cv_text}\n\n"
        f"Job description:\n{job_text}\n\n"
        "Return the improved CV text."
    )

    try:
        response = client.models.generate_content(
            model=settings.gemini_model,
            contents=prompt,
        )
    except genai_errors.ClientError as exc:
        message = str(exc)
        status_code = _map_gemini_error_to_status(message)
        logger.warning("Gemini client error: %s", message)
        raise LLMServiceError(f"GEMINI_ERROR: {message}", status_code=status_code) from exc
    except Exception as exc:
        message = str(exc)
        logger.exception("Gemini unexpected error: %s", message)
        raise LLMServiceError(f"GEMINI_ERROR: {message}", status_code=503) from exc

    optimized_cv = (getattr(response, "text", "") or "").strip()
    if not optimized_cv:
        raise LLMServiceError("GEMINI_ERROR: empty response", status_code=502)
    return LLMResult(
        optimized_cv=optimized_cv,
        feedback="Generated by Gemini API.",
    )


def _truncate(value: str, limit: int) -> str:
    if limit <= 0:
        return ""
    if len(value) <= limit:
        return value
    return value[:limit].rstrip()


@lru_cache(maxsize=1)
def _get_gemini_client() -> genai.Client:
    return genai.Client(api_key=settings.gemini_api_key)


def _map_gemini_error_to_status(message: str) -> int:
    lowered = message.lower()
    if "resource_exhausted" in lowered or "quota" in lowered:
        return 429
    if "permission_denied" in lowered or "unauthorized" in lowered or "api key" in lowered:
        return 401
    if "deadline" in lowered or "timeout" in lowered or "unavailable" in lowered:
        return 503
    return 502
